### ISSUE TITLE
Missing files to build project 

### ISSUE THREAD

**Issue by ssabug** [alxtim10/AngklungBeats#1]
Hi,

I tried to build AngklungBeats for linux by editing the *.jucer file.

The following files are missing, in the **Binary data** section:
- AngklungHigh3.wav
- AngklungLow3.wav
- AngklungMed3.wav
- wallpaperBambu.png

Could you please provide the files ? thank you

**Comment by alxtim10** [comment]
Here you go

https://drive.google.com/file/d/1cMB1rA6zmeHs73xO7n-hUGJQYTSmtkdG/view?usp=sharing

**Comment by ssabug** [comment]
Thank you :)

After commenting the `#include <windows.h>' line in **PluginEditor.cpp** , it builded successfully a linux VST3 

Plugin working on Bitwing / Fedora Linux
